Convert Login from VATUSA to VATSIM Connect
zabartcc/api pull request #6
Opened 2022-11-09 21:00 UTC by cdconn00

This PR:

- Adds oauth middleware.
- Adds helper to communicate with VATSIM API.
- Modifies the login/verify endpoint to utilize vatsim connect instead of VATUSA ULS.

2022-11-09 21:04 UTC, cdconn00 commented
@Frafire on the usercontroller just review the 

endpoint starting with `router.post("/login", oAuth, async (req, res) => {` the rest is just formatting.

2022-11-10 14:47 UTC, Frafire requested changes
Small check require in UserController line **3**,  **334**,  **437**

2022-11-10 15:24 UTC, Frafire requested changes

2022-11-10 15:27 UTC, cdconn00 commented on controllers/UserController.js
Yes, line three is blank because their is an assignment before it. I didn't write this code, I don't think it's worth refactoring at the moment.

2022-11-10 15:29 UTC, cdconn00 commented on controllers/UserController.js
I also did not write the code on 334, it is fine for now. About 437, files should end with a blank line.

2022-11-10 17:50 UTC, cdconn00 commented
Needs https://github.com/zabartcc/api/pull/8 to be merged first

Should be merged alongside https://github.com/zabartcc/ui/pull/13

2022-11-10 20:15 UTC, Frafire approved these changes

2022-11-10 20:17 UTC, merged